name = "Sanglicraft"
author = "Witz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f71ab017515f7e4a3a2c63a2253af1b914300988bf0c44dfa2aef89c91b33d08"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
