name = "Sanglicraft"
author = "Witz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b66c40ed97fbab4eb3facbce199c8b8214d0216485006eedcab0f6433e00134"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
