name = "Sanglicraft"
author = "Witz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8980465be9acf4fefd8d3d11358ca0c1a3a8c98b6d22532566ed113d6d943b52"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
